- name: nginx install and run
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.debug:
      msg: "installing nginx and to run it"
  - name: install nginx packages
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx packages
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

- name: install nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"
  - name: install nginx if debain
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debain"

- name: installing packages
  hosts: web
  become: yes
  tasks:
  - name: installing multiple packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - postfix
    - httpd

- name: create ec2 and r53
  hosts: local
  connection: local
  vars:
    subnet_id: "subnet-006b392f9429ec396"
    sg_id: "sg-0fe656c7eda0c607b"
    ami_id: "ami-09c813fb71547fc4f"
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances