- name: nginx install and run
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.debug:
      msg: "installing nginx and to run it"
  - name: install nginx packages
    ansible.builtin.packages:
      name: nginx
      state: present
  - name: run nginx packages
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes