- name: installing packages
  hosts: web
  become: yes
  tasks:
  - name: installing multiple packages
    tasks:
    - name: instll all
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
    - name:
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
      - mysql
      - nginx
      - postfix
      - httpd

  # - name: runnig multiple packages
  #   ansible.builtin.service:
  #     name: "{{ item }}"
  #     state: started
  #   loop:
  #   - mysql
  #   - nginx
  #   - postfix
  #   - httpd